version: '2'
services:
  nginx:
      image: ihaohong/nginx
      ports:
        - "80:80"
#      links:
#        - "php"
      volumes:
        - ~/opt:/opt

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
    db_data: